namespace Xlflow.ExcelBridge.Services;

public sealed record EditCommandArguments(
    string Action,
    string WorkbookPath,
    bool Visible,
    string Sheet,
    string Cell,
    string RangeAddress,
    string Rows,
    string Columns,
    string Value,
    bool ValueSpecified,
    string Formula,
    bool FormulaSpecified,
    string FormulaR1C1,
    bool FormulaR1C1Specified,
    string Fill,
    string Clear,
    string Height,
    string Width,
    string Events,
    bool Calculate,
    bool UseSession,
    string MetadataPath);
