namespace Xlflow.ExcelBridge.Services;

public sealed record RunCommandArguments(
    string WorkbookPath,
    string MacroName,
    string MacroArgsJSON,
    bool Visible,
    bool DisplayAlerts,
    bool SaveWorkbook,
    bool Direct,
    bool Diagnostic,
    bool SuppressModalErrors,
    string MsgBoxResponsesJSON,
    string InputResponsesJSON,
    string FileDialogResponsesJSON,
    bool DebugStreamEnabled,
    string DebugStreamPipeName,
    bool UIStreamEnabled,
    string UIStreamPipeName,
    bool UIStreamRedactInput,
    bool UseSession,
    string MetadataPath,
    string RuntimeMode,
    string RuntimeSource,
    string SaveAsPath,
    int TimeoutSeconds);
