namespace Xlflow.ExcelBridge.Services;

public sealed record TestCommandArguments(
    string WorkbookPath,
    string Filter,
    string ModuleFilter,
    string TagFilter,
    bool Visible,
    string RuntimeMode,
    string RuntimeSource,
    string MsgBoxResponsesJSON,
    string InputResponsesJSON,
    string FileDialogResponsesJSON,
    bool DebugStreamEnabled,
    string DebugStreamPipeName,
    bool UIStreamEnabled,
    string UIStreamPipeName,
    bool UIStreamRedactInput,
    bool UseSession,
    string Isolation = "none",
    bool NoSave = false,
    bool FailFast = false,
    int MaxFailures = 0,
    int RerunFailed = 0,
    bool DisableAutoSession = true,
    string SourceWorkbookPath = "",
    string ProjectRoot = "",
    string TempRunRoot = "",
    string MetadataPath = "");
